# Build settings
markdown: kramdown

title: "Zhaoyu Xing's Photography"
description: "A collection of moments captured through my lens."
author: "Zhaoyu Xing"
email: "zxing@nd.edu"
social: 

# 【关键配置】
baseurl: "/photography"
url: "https://ZhaoyuXingStat.github.io"

# Social settings
social-links:
  github: ZhaoyuXingStat
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
